name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Self test
        id: selftest
        uses: syslabtec/pubsub@master
        with:
          include: "docs/"
          find: "world"
          replace: "world"
      - name: Check outputs and modified files
        run: |
          test "${{ steps.selftest.outputs.modifiedFiles }}" == "1"
          grep "Hello world" docs/note.txt          
