name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Self test
        id: selftest
        uses: syslabtec/pubsub@master
        env:
          INPUT_NAME: "John" 
      - name: Check outputs and modified files
        run: |
          echo "${{ steps.selftest.outputs.stdout }}"
