name: Manually Trigger
on:
  # This workflow will never trigger automatically.
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          echo "This workflow was triggered manually."
