name: Secure Workflow

on:
  workflow_dispatch:
    inputs:
      secret_input:
        description: "Enter the secret token"
        required: true
        default: ""

jobs:
  secure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check secret input
        if: ${{ github.event.inputs.secret_input != secrets.SECRET_TOKEN }}  # Corrected
        run: |
          echo "Invalid secret input!"
          exit 1  # Terminate the workflow

      - name: Allowed actions
        if: ${{ github.event.inputs.secret_input == secrets.SECRET_TOKEN }}  # Corrected
        run: |
          echo "Authorized actions will execute here"
          # Perform your secure workflow tasks
