
name: Secure Workflow

on:
  workflow_dispatch:
    inputs:
      secret_input:
        description: "Enter the secret token"
        required: true
        default: ""

jobs:
  secure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Print
        run: | 
          echo ${{ github.event.inputs.secret_input }}
          echo ${{ secrets.SECRET_TOKEN }}
      - name: Match
        env:
          MY_ENV_VAR: ${{ secrets.SECRET_TOKEN }}
        if: ${{ github.event.inputs.user_input == MY_ENV_VAR }}
        run: |
          echo "Input matches secret!"
          
      # - name: Check secret input
      #   if: ${{ github.event.inputs.secret_input }} != ${{secrets.SECRET_TOKEN }}  # Corrected
      #   run: |
      #     echo "Invalid secret input!"
      #     exit 1  # Terminate the workflow

      # - name: Allowed actions
      #   if: ${{ github.event.inputs.secret_input }} == ${{secrets.SECRET_TOKEN }}  # Corrected
      #   run: |
      #     echo "Authorized actions will execute here"
      #     # Perform your secure workflow tasks
