
name: Secure Workflow 2

on:
  workflow_dispatch:
    inputs:
      secret_input:
        description: "Enter the secret token"
        required: true
        default: ""
env:
  AUTHENTICATE_TOKEN : ${{ secrets.SECRET_TOKEN }}

jobs:
  secure_job:
    if: github.event.inputs.secret_input == var.VAR_AUTH   # Correctet
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Allowed actions
        run: |
          echo "Authorized actions will execute here"
          # Perform your secure workflow tasks

      - name: Step1 
        if: ${{ success() }} 
        run: | 
          echo "Hello"
